# Banco H2
spring.datasource.url=jdbc:h2:mem:ticketmaster
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Chave da API Ticketmaster (nunca colocar no código-fonte)
ticketmaster.api.key=vm4lEvubTEujseI2pY6GZk77Tn5gH8Y7