# Banco de dados H2 (em memória)
spring.datasource.url=jdbc:h2:mem:ticketmaster;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Console H2 — acessar em /h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Swagger UI — acessar em /swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=method

# API externa Ticketmaster
ticketmaster.api.key=vm4lEvubTEujseI2pY6GZk77Tn5gH8Y7